[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
myepicproject = "3uCGttvR5yP62bjWbMifHPsj64Yq5UkveAhvsghpi8vt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/thiago/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
